nginx:
  build: nginx
  volumes:
    - ../laravel/:/laravel
  command: nginx -g "daemon off;"
  links:
    - php
  ports:
    - "80:80"
php:
  build: .
  volumes:
    - ../laravel/:/laravel
  working_dir: /laravel
  command: php-fpm7.0
  links:
    - mysql
  ports:
    - "7000:7000"
  environment:
    APP_ENV: local
    APP_DEBUG: 'true'
    QUEUE_DRIVER: database
    DB_CONNECTION: mysql
    DB_HOST: mysql
    DB_DATABASE: map
    DB_USERNAME: root
    DB_PASSWORD: secret
mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: map
    MYSQL_USER: root
    MYSQL_PASSWORD: secret